### ISSUE TITLE
Events are not added as posts

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#127]
When a new event is created, it only appears at the top of the main page and not as a post. For example, see Tech Industry Night event and Professional Photoshoot event which are both added to the events folder but only the latter is shown as a post  on the main page. Currently, I am unsure about which behaviour is the correct one, though I am personally leaning towards the second behaviour 🤔 

This issue may also be linked with #124. 

 This might be related to the change in submodule dependency that happened https://github.com/ubccsss/ubccsss.org/pull/80

**Comment by kewbish** [comment]
From a cursory look, I think this is the intended behaviour. If you look at the sidebar when looking at any post / event, events + posts both show up under the 'Recent Posts'. As well, the old Headshot Session event is shown on the main page, even though it has an event type.

I think they're just not showing on the main page because they're still in the top promotion header? I could be wrong, but that's my hypothesis for now.
