### ISSUE TITLE
Broken labels 

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#177]
Many labels and headers are broken after #163 . This might be because we removed the hugo-bootstrap submodule. Please check ASAP!

This seems to be missing the "tags" and "category" text
![image](https://user-images.githubusercontent.com/37171109/160218647-4d510d82-d7de-41f3-b793-f001d8121d1d.png)
We are missing several headers here, including recent post, tags, category
![image](https://user-images.githubusercontent.com/37171109/160218652-7505ec28-e75a-4687-ad53-1b5c537fab5c.png)

**Comment by AnimeAllstar** [comment]
On it.

**Comment by AnimeAllstar** [comment]
Readding the submodule did not change anything. It was not used at all.

**Comment by eqfy** [comment]
Ok so it is not a easy fix then... Some other part of the migration probably went wrong. 

In the worst case, we can revert #163 but let's try to figure out what's happening first

**Comment by AnimeAllstar** [comment]
@eqfy I figured it out. In [https://github.com/ubccsss/hugo-bootstrap-5/commit/46b0b7469ff05fcccafd2d1af19e93b79534cdc9](https://github.com/ubccsss/hugo-bootstrap-5/commit/46b0b7469ff05fcccafd2d1af19e93b79534cdc9), @kewbish overwrote the files instead of merging each file. So, if something was present in the theme repo but not in the ubccsss.org repo, it'll be missing because previously, if Hugo couldn't find something in ubccsss.org's files, it'd search the theme repo. This is 

![image](https://user-images.githubusercontent.com/39626451/160219583-56ade15f-91e2-4a3f-a6c0-d2cfb77c2c28.png)

I think we should just revert, cause in order to successfully merge, we'll probably have to merge all the files in the theme repo and not replace them.

**Comment by eqfy** [comment]
Yes, that's a good idea. Lets try to merge i18n/en.yaml first. If that doesn't work (if there are more issues), then we can revert everything in #163

**Comment by AnimeAllstar** [comment]
@eqfy are there any other bugs? or did that solve it.

**Comment by eqfy** [comment]
Yes I just verified everything in production. It seems everything is fixed. Will keep an eye out for potential issues. Thanks a lot @AnimeAllstar !
