### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by NotWoods** [ubccsss/ubccsss.org#21]
Add a search bar to the website using [Algolia](https://www.algolia.com/) or a Google custom search.

**Comment by RamitKataria** [comment]
I'm working on integrating Google's custom search. There are several ways to do this so I would like some suggestions. @eqfy @kewbish @AnimeAllstar 

[Here](https://github.com/RamitKataria/ubccsss.org/commit/81c91fe2cdf5e56866ec6511a773a3bc3d35da38) is a simple prototype that does not require any significant changes to our layout and [here](https://61d645c48b61d20007600db4--ramit-csss.netlify.app/) is the preview.

I was trying to have the search bar on the right end of the menu bar. I don't have much experience with hugo but based on my current knowledge and things I've tried, this is not possible without making changes to the theme, which is [a submodule](https://github.com/NotWoods/hugo-bootstrap-5/tree/4c167a9165e0d7feda10b4c72c8f4baef8e70d45) not owned by CSSS. So, it's the under the menu bar for now and needs to be manually added to all the pages (currently I've only added it to the home page). Furthermore, when I locally modified the theme to try to make it work, the search bar was diagonal just like the menu bar (which seems good enough) but there is an issue with displaying results using the current overlay layout (other options for layouts below).

Here are the layout options:
![image](https://user-images.githubusercontent.com/42333514/148314772-77cfe85c-51e6-4c2b-b0bc-5dcd14764d9a.png)
Out of all of these, only the overlay (what I'm currently using and two-page (search box stays the same but the results appear on another page) look good to me. Others would negatively impact our website layout, in my opinion. Using the two-page would solve the issue related to displaying results since they would be displayed on another page.

I'm currently using my personal Google account but we should eventually use the CSSS-owned Google account for this.

Also, there's many parameters we can tweak for the search results and that's controlled on Google's Control Panel but we can discuss them once we have the layout working.

**Comment by NotWoods** [comment]
You can override theme files by adding files inside `layouts`, just use the same filename. For example, `layouts/_default/single.html` overrides `theme/hugo-bootstrap-5/_default/single.html`.

**Comment by NotWoods** [comment]
You can also "undo" the 2 degree rotation by using the opposite rotation on an element. The [logo does this](https://github.com/ubccsss/ubccsss.org/blob/master/assets/css/styles.css#L36) with the `transform: rotateZ(2deg);` CSS rule.

**Comment by RamitKataria** [comment]
Thanks!

**Comment by RamitKataria** [comment]
I've fixed the rotation but the issue with displaying results still exists.

[Working branch](https://github.com/RamitKataria/ubccsss.org/tree/gcse-search) | [Preview](https://gcse-search--ramit-csss.netlify.app/)

I've been trying to figure out the solution but no success yet. However, I found that the overlay has issues when I add a transform rotation property that is not none as well as when it is rotated (by the parent element). Setting the transform to none keeps the rotation consistent with the parent but setting it to undo the rotation requires setting transform to rotate. It seems like the way Google calculates where to place the overlay doesn't work well with rotations (or undoing rotations).

Anyone have any ideas? I will try to investigate more another day.

Also, I haven't submitted a PR for this yet because it is not even close to being usable but let me know if it would be more convenient to review and discuss this in a PR.

**Comment by AnimeAllstar** [comment]
@RamitKataria you could use this style for the search bar in the nav:
```
<form class="d-flex">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-light" type="submit">Search</button>
</form>
```
from [here](https://getbootstrap.com/docs/5.0/components/navbar/?#color-schemes)

**Comment by RamitKataria** [comment]
Looks good, thanks!
