### ISSUE TITLE
Integrate the course review difficulty slider.

### ISSUE THREAD

**Issue by shubhbhalla** [ubccsss/ubccsss.org#245]
Right now, all course reviews have an option to specify the course difficulty and rating.
Let's try to have an overall rate for the course on the course webpage so that we know what is the overall score assigned to a course by all users.

**Comment by AnimeAllstar** [comment]
The current implementation is done using markdown files: https://github.com/ubccsss/ubccsss.org/blob/master/content/services/courses/cpsc-304.md?plain=1

We'd have to figure out a better way to store course content data if we want to automate more complex operations like averaging course review scores. Maybe instead of storing markdown files, we could consider storing the course reviews in a database. We can make the database call in the Cloudflare worker. @kewbish What are your thought on this?

**Comment by AnimeAllstar** [comment]
Or we could use some regex to locate scores and average them.

**Comment by kewbish** [comment]
Jason brought up the idea of using a database too - to me it feels a bit overkill to have to rely on another service for that, but I'm open to the idea!

We already have a count parameter in the Markdown - could we also add 'current average difficulty' and 'current average overall quality' parameters to the frontmatter and calculate the average from there? When generating a review issue, we could read the current average difficulty, multiply by count, add the review data and re-average. This is rather janky though.

Another idea might be to move all the course reviews into JSON data (in the realm of Hugo) and generate course review issues in that format instead. Then when rendering the page we can calculate the overall score + use a partial for each review.

I'm leaning towards the JSON-data idea rather than a full-fledged DB.

**Comment by AnimeAllstar** [comment]
The JSON idea is definitely better for Hugo since a DB would be overkill.

**Comment by shubhbhalla** [comment]
If we don't foresee using a DB for anything major in the near future then the JSON idea is fine with me too!
