### ISSUE TITLE
Slanting navbar button on mobile devices

### ISSUE THREAD

**Issue by AnimeAllstar** [ubccsss/ubccsss.org#78]
### Problem:

![image](https://user-images.githubusercontent.com/39626451/140623715-67a57a2d-39d1-4bfc-a60f-3eb79c036074.png)

### Cause:

`.blog-header .navbar` has the css property `transform: rotateZ(-2deg);`, which causes the slanting navbar, and hence the slanting navbar button for the menu. I believe that this is by design.

### Solutions:

- we could remove the property entirely, which would make the navbar horizontal both on the mobile and on the desktop
- we could keep it slanting on desktop and make it horizontal on mobile devices.

**Comment by kewbish** [comment]
I think what Eric might have meant is that the navbar button doesn't work (i.e. when I click it, nothing happens.) I'm not too familiar with Bootstrap, but it seems that it has something to do with a [collapse plugin](https://getbootstrap.com/docs/5.0/components/collapse/#via-data-attributes).

The issue seems to be that we were using the syntax for Bootstrap 4.0 instead of Bootstrap 5.0 (using the data-toggle attribute instead of data-bs-toggle, and data-target instead of data-bs-target). I played around locally with Inspect Element, and when I make those changes, it seems to work fine.

This should be a quick fix - I can take this on.
