### ISSUE TITLE
Course database create entry UI

### ISSUE THREAD

**Issue by eqfy** [ubccsss/ubccsss.org#91]
Currently, our course database is updated by having the visitor go to GitHub, make changes to the markdown, and submit a pull request. However, this is cumbersome and might scare students unfamiliar with GitHub/Markdown. Hence, it is probably a good idea to have some sort of UI for submitting course reviews directly on our website. Although it is possible to just have a Google forms there, it will be really nice if we can automatically create PRs after user submits a review.

**Comment by AnimeAllstar** [comment]
- add ui
- create github issue on submit

**Comment by AnimeAllstar** [comment]
I'm gonna work on this post-finals

**Comment by AnimeAllstar** [comment]
![image](https://user-images.githubusercontent.com/39626451/148673939-b3056c00-215b-4020-9dac-4a2787d66959.png)

So, I have created a simple UI for the form. However, I just realized something: 
Only users with ["pull access to a repository can create an issue"](https://docs.github.com/en/rest/reference/issues#create-an-issue).

So, since users do not have pull access, they won't be able to make a direct call to the GitHub API with a POST request.

My solution:

Create a simple server that will accept a POST request to create an issue. This server will have an access token that allows it to create issues.

User clicks submit -> POST request to our server -> our server makes POST request GitHub to create an issue in ubccsss.org.

It should be a fairly straightforward express server, lemme know what you'll think about it. Or if there is a better solution. @eqfy @RamitKataria @kewbish

**Comment by AnimeAllstar** [comment]
![image](https://user-images.githubusercontent.com/39626451/148689938-b2688af8-2b05-4443-8623-10950ae36cc8.png)

I have created the UI for creating new issues. However, after reading the docs, I realized that only users with ["pull access to a repository can create an issue"](https://docs.github.com/en/rest/reference/issues#create-an-issue).

The way that this is done is that the user creates an access token and uses it to make POST requests. However, this means that any random person can't just make a POST request, which makes sense.

I tried playing around with HUGO environment variables {{ os.Getenv "ACCESS_TOKEN" }}, but ultimately, they get exposed to the public and if someone uses inspect-element, they'll be able to copy the access token.

My solution:

Make a simple express server that has a dotenv variable containing the access token.

When the user clicks submit, ubccsss.org makes a POST request to the server and then the server makes a POST request to GitHub. That way, the access token will remain a secret and anonymous people will be able to make issues using the form.

This should be fairly straightforward. I'll make another repo with the server, test it and then transfer ownership to ubccss. Lemme know what y'all think and if you know of any other method. @eqfy @RamitKataria @kewbish 

I'm just not sure where we will host this server, it will barely require any computing power since it's just gonna route the POST request to GitHub and it's main purpose is to hide the access token.

**Comment by kewbish** [comment]
Wow - this looks super cool :)

RE the hosting - if we're not expecting this to be run too frequently, [Cloudflare Workers](https://workers.cloudflare.com/) could be an option. It's like a functions-as-a-service platform, and it might be easier than trying to host on Heroku or something. There's a very generous free tier - 100k requests a day. Just an idea!

**Comment by AnimeAllstar** [comment]
@kewbish Sounds good, I'll check it out rn.

**Comment by AnimeAllstar** [comment]
@kewbish Cloudflare Workers are super convenient.

I made [this](https://github.com/ubccsss/ubccsss.org/issues/111) issue using the worker. I'll do some more testing and it should be ready.

**Comment by AnimeAllstar** [comment]
@eqfy I need a new email id that will create the issues. Right now, it's using my account, could you make a new one and share the credentials on slack?

**Comment by eqfy** [comment]
@AnimeAllstar Thanks for all the great work done so far! I messaged you on slack
